server:
  port: 8100
  servlet:
    context-path: /spring-boot-project/nacos-dubbo-project

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traum?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 621248
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: /mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true

dubbo:
  application:
    name: service-1
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: interface
    parameters:
      namespace: dong-dev
  protocol:
    name: dubbo
    #dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1

nacos:
  config:
    bootstrap:
      enable: true
    # 主配置服务器地址
    server-addr: 127.0.0.1:8848
    namespace: dong-dev
    # 主配置 data-id
    data-id: dong
    # 主配置 group-id
    group: DEFAULT_GROUP
    # 主配置 配置文件类型
    type: properties
    # 主配置 最大重试次数
    max-retry: 10
    # 主配置 开启自动刷新
    auto-refresh: true
    # 主配置 重试时间
    config-retry-time: 2333
    # 主配置 配置监听长轮询超时时间
    config-long-poll-timeout: 46000
    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    enable-remote-sync-config: true
