package com.dtr.sp.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.dtr.sp.bean.TcUser;

public interface TcUserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    int insert(TcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    int insertSelective(TcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    TcUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    int updateByPrimaryKeySelective(TcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbg.generated Tue Dec 01 21:46:20 CST 2020
     */
    int updateByPrimaryKey(TcUser record);
}