server:
  port: 8090
  servlet:
    context-path: /spring-boot-project/nacos

knife4j:
  enable: true

nacos:
  config:
    bootstrap:
      enable: true
    # 主配置服务器地址
    server-addr: 127.0.0.1:8848
    # 主配置 data-id
    data-id: dong
    # 主配置 group-id
    group: DEFAULT_GROUP
    # 主配置 配置文件类型
    type: properties
    # 主配置 最大重试次数
    max-retry: 10
    # 主配置 开启自动刷新
    auto-refresh: true
    # 主配置 重试时间
    config-retry-time: 2333
    # 主配置 配置监听长轮询超时时间
    config-long-poll-timeout: 46000
    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    enable-remote-sync-config: true
  ext-config:
    - data-id: test
      group: DEFAULT_GROUP
      max-retry: 10
      type: yaml
      auto-refresh: true
      config-retry-time: 2333
      config-long-poll-timeout: 46000
      enable-remote-sync-config: true