server:
  port: 8080
  servlet:
    context-path: /spring-boot-project/mybatis-plus

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traum?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 621248
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: /mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true