server:
  port: 8080
  servlet:
    context-path: /jpa-project/jpa

spring:
  datasource:
    url: jdbc:mysql://fms-dev3.in.htw.link:3810/coder?useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: htw123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true